spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://example.org
          predicates:
            - Path=/
        - id: eureka
          uri: lb://eureka
          predicates:
            - Path=/eureka
          filters:
            - StripPrefix=1 # https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#the-stripprefix-gatewayfilter-factory
        - id: eureka-static
          uri: lb://eureka
          predicates:
            - Path=/eureka/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true