spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/demo-jpa
    url: jdbc:hsqldb:mem:localhost/demo-jpa
    username: root
    password: admin
#    driver-class-name: org.hsqldb.jdbc.JDBCDriver
#  data:
#    rest:
#      defaultMediaType: application/json
#  hateoas:
#    use-hal-as-default-json-media-type: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

local:
  zone: Asia/Shanghai