spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/demo-jpa
    url: jdbc:hsqldb:mem:localhost/demo-jpa
    username: root
    password: admin
#    driver-class-name: org.hsqldb.jdbc.JDBCDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

local:
  zone: Asia/Shanghai